### ISSUE TITLE
Feature: [Collectable Badges]

### ISSUE THREAD

**Issue by Camology** [yeSpud/MACSTransitApp#46]
Add an ability to collect badges, for example:
* Rode the red line 69 times
* Rode every color of the rainbow in order, as a busline in one day
* rode the bus without paying your fare, bad boy
* Rode from UAF to North Pole and then back 24 hours later. Survive in North Pole for a night!!
* rode the bus at -40* or colder!!

**Comment by yeSpud** [comment]
From the given explanation and provided examples, it appears that this feature request does not fit the current scope of the project. 

The current implementation of the MACS Transit App is a simple bus tracking utility. Having an achievement/badge like system would make this seem less like a tool and more like a game (I don't think the town would appreciate the misuse of its services).

If you would like to fork this project and implement this feature yourself then you are welcome to do so, but for the extent of this project, this feature request does not apply.
